import { ConfigurationOptions } from '../../../org/bukkit/configuration/ConfigurationOptions.js';
import { ConfigurationSection } from '../../../org/bukkit/configuration/ConfigurationSection.js';
import { Location } from '../../../org/bukkit/Location.js';
import { OfflinePlayer } from '../../../org/bukkit/OfflinePlayer.js';
import { Vector } from '../../../org/bukkit/util/Vector.js';
import { ConfigurationSerializable } from '../../../org/bukkit/configuration/serialization/ConfigurationSerializable.js';
import { Color } from '../../../org/bukkit/Color.js';
import { ItemStack } from '../../../org/bukkit/inventory/ItemStack.js';
export interface Configuration extends ConfigurationSection {
    options(): ConfigurationOptions;
    setDefaults(arg0: Configuration): void;
    addDefaults(arg0: Configuration): void;
    addDefaults(arg0: any): void;
    getDefaults(): Configuration;
    addDefault(arg0: string, arg1: any): void;
    get(arg0: string): any;
    get(arg0: string, arg1: any): any;
    getObject(arg0: string, arg1: any, arg2: any): any;
    getObject(arg0: string, arg1: any): any;
    getBoolean(arg0: string): boolean;
    getBoolean(arg0: string, arg1: boolean): boolean;
    getInt(arg0: string, arg1: number): number;
    getInt(arg0: string): number;
    getLong(arg0: string, arg1: number): number;
    getLong(arg0: string): number;
    getDouble(arg0: string): number;
    getDouble(arg0: string, arg1: number): number;
    getName(): string;
    contains(arg0: string): boolean;
    contains(arg0: string, arg1: boolean): boolean;
    getParent(): ConfigurationSection;
    set(arg0: string, arg1: any): void;
    getLocation(arg0: string, arg1: Location): Location;
    getLocation(arg0: string): Location;
    isSet(arg0: string): boolean;
    getRoot(): Configuration;
    getKeys(arg0: boolean): any;
    getString(arg0: string): string;
    getString(arg0: string, arg1: string): string;
    isBoolean(arg0: string): boolean;
    isString(arg0: string): boolean;
    getOfflinePlayer(arg0: string, arg1: OfflinePlayer): OfflinePlayer;
    getOfflinePlayer(arg0: string): OfflinePlayer;
    isConfigurationSection(arg0: string): boolean;
    getConfigurationSection(arg0: string): ConfigurationSection;
    getList(arg0: string, arg1: any): any;
    getList(arg0: string): any;
    isItemStack(arg0: string): boolean;
    getDoubleList(arg0: string): any;
    getCurrentPath(): string;
    isInt(arg0: string): boolean;
    getFloatList(arg0: string): any;
    getVector(arg0: string): Vector;
    getVector(arg0: string, arg1: Vector): Vector;
    isDouble(arg0: string): boolean;
    isLong(arg0: string): boolean;
    isList(arg0: string): boolean;
    getDefaultSection(): ConfigurationSection;
    getLongList(arg0: string): any;
    getSerializable(arg0: string, arg1: any, arg2: ConfigurationSerializable): ConfigurationSerializable;
    getSerializable(arg0: string, arg1: any): ConfigurationSerializable;
    getByteList(arg0: string): any;
    isOfflinePlayer(arg0: string): boolean;
    getColor(arg0: string): Color;
    getColor(arg0: string, arg1: Color): Color;
    isLocation(arg0: string): boolean;
    getCharacterList(arg0: string): any;
    getBooleanList(arg0: string): any;
    createSection(arg0: string, arg1: any): ConfigurationSection;
    createSection(arg0: string): ConfigurationSection;
    getStringList(arg0: string): any;
    getIntegerList(arg0: string): any;
    getValues(arg0: boolean): any;
    getItemStack(arg0: string, arg1: ItemStack): ItemStack;
    getItemStack(arg0: string): ItemStack;
    isColor(arg0: string): boolean;
    getShortList(arg0: string): any;
    isVector(arg0: string): boolean;
    getMapList(arg0: string): any;
}
export declare class Configuration {
    static get $javaClass(): any;
}
