import Attribute from '../../../../org/bukkit/attribute/Attribute.js';
import AttributeModifier from '../../../../org/bukkit/attribute/AttributeModifier.js';
import Color from '../../../../org/bukkit/Color.js';
import CustomItemTagContainer from '../../../../org/bukkit/inventory/meta/tags/CustomItemTagContainer.js';
import Enchantment from '../../../../org/bukkit/enchantments/Enchantment.js';
import EquipmentSlot from '../../../../org/bukkit/inventory/EquipmentSlot.js';
import ItemFlag from '../../../../org/bukkit/inventory/ItemFlag.js';
import ItemMeta from '../../../../org/bukkit/inventory/meta/ItemMeta.js';
import Multimap from '../../../../com/google/common/collect/Multimap.js';
import PersistentDataContainer from '../../../../org/bukkit/persistence/PersistentDataContainer.js';
import PotionData from '../../../../org/bukkit/potion/PotionData.js';
import PotionEffect from '../../../../org/bukkit/potion/PotionEffect.js';
import PotionEffectType from '../../../../org/bukkit/potion/PotionEffectType.js';
export default interface PotionMeta extends ItemMeta {
    clone(): PotionMeta;
    clone(): ItemMeta;
    clone(): any;
    getColor(): Color;
    setColor(arg0: Color): void;
    addCustomEffect(arg0: PotionEffect, arg1: boolean): boolean;
    clearCustomEffects(): boolean;
    hasCustomEffect(arg0: PotionEffectType): boolean;
    setBasePotionData(arg0: PotionData): void;
    getBasePotionData(): PotionData;
    hasCustomEffects(): boolean;
    removeCustomEffect(arg0: PotionEffectType): boolean;
    getCustomEffects(): Array<PotionEffect>;
    hasColor(): boolean;
    setMainEffect(arg0: PotionEffectType): boolean;
    getDisplayName(): string;
    hasEnchant(arg0: Enchantment): boolean;
    getEnchantLevel(arg0: Enchantment): number;
    getEnchants(): any;
    setLore(arg0: Array<any>): void;
    setUnbreakable(arg0: boolean): void;
    removeEnchant(arg0: Enchantment): boolean;
    setVersion(arg0: number): void;
    getLore(): Array<string>;
    setDisplayName(arg0: string): void;
    isUnbreakable(): boolean;
    addEnchant(arg0: Enchantment, arg1: number, arg2: boolean): boolean;
    hasDisplayName(): boolean;
    hasLocalizedName(): boolean;
    getLocalizedName(): string;
    getItemFlags(): any;
    hasItemFlag(arg0: ItemFlag): boolean;
    hasCustomModelData(): boolean;
    addItemFlags(arg0: Array<ItemFlag>): void;
    removeItemFlags(arg0: Array<ItemFlag>): void;
    setLocalizedName(arg0: string): void;
    hasEnchants(): boolean;
    hasLore(): boolean;
    getCustomModelData(): number;
    setCustomModelData(arg0: any): void;
    hasConflictingEnchant(arg0: Enchantment): boolean;
    hasAttributeModifiers(): boolean;
    getAttributeModifiers(): Multimap;
    getAttributeModifiers(arg0: EquipmentSlot): Multimap;
    getAttributeModifiers(arg0: Attribute): any;
    addAttributeModifier(arg0: Attribute, arg1: AttributeModifier): boolean;
    removeAttributeModifier(arg0: Attribute): boolean;
    removeAttributeModifier(arg0: Attribute, arg1: AttributeModifier): boolean;
    removeAttributeModifier(arg0: EquipmentSlot): boolean;
    setAttributeModifiers(arg0: Multimap): void;
    getCustomTagContainer(): CustomItemTagContainer;
    serialize(): any;
    getPersistentDataContainer(): PersistentDataContainer;
}
export default class PotionMeta {
    static get $javaClass(): any;
}
