import { NamespacedKey } from '../../../org/bukkit/NamespacedKey.js';
import { Keyed } from '../../../org/bukkit/Keyed.js';
export interface EntityType extends Keyed {
    getEntityClass(): any;
    getTypeId(): number;
    isSpawnable(): boolean;
    getName(): string;
    getKey(): NamespacedKey;
    isAlive(): boolean;
    name(): string;
    compareTo(arg0: any): number;
    compareTo(arg0: any): number;
    getDeclaringClass(): any;
    ordinal(): number;
}
export declare class EntityType {
    static get $javaClass(): any;
    static get DROPPED_ITEM(): EntityType;
    static get EXPERIENCE_ORB(): EntityType;
    static get AREA_EFFECT_CLOUD(): EntityType;
    static get ELDER_GUARDIAN(): EntityType;
    static get WITHER_SKELETON(): EntityType;
    static get STRAY(): EntityType;
    static get EGG(): EntityType;
    static get LEASH_HITCH(): EntityType;
    static get PAINTING(): EntityType;
    static get ARROW(): EntityType;
    static get SNOWBALL(): EntityType;
    static get FIREBALL(): EntityType;
    static get SMALL_FIREBALL(): EntityType;
    static get ENDER_PEARL(): EntityType;
    static get ENDER_SIGNAL(): EntityType;
    static get SPLASH_POTION(): EntityType;
    static get THROWN_EXP_BOTTLE(): EntityType;
    static get ITEM_FRAME(): EntityType;
    static get WITHER_SKULL(): EntityType;
    static get PRIMED_TNT(): EntityType;
    static get FALLING_BLOCK(): EntityType;
    static get FIREWORK(): EntityType;
    static get HUSK(): EntityType;
    static get SPECTRAL_ARROW(): EntityType;
    static get SHULKER_BULLET(): EntityType;
    static get DRAGON_FIREBALL(): EntityType;
    static get ZOMBIE_VILLAGER(): EntityType;
    static get SKELETON_HORSE(): EntityType;
    static get ZOMBIE_HORSE(): EntityType;
    static get ARMOR_STAND(): EntityType;
    static get DONKEY(): EntityType;
    static get MULE(): EntityType;
    static get EVOKER_FANGS(): EntityType;
    static get EVOKER(): EntityType;
    static get VEX(): EntityType;
    static get VINDICATOR(): EntityType;
    static get ILLUSIONER(): EntityType;
    static get MINECART_COMMAND(): EntityType;
    static get BOAT(): EntityType;
    static get MINECART(): EntityType;
    static get MINECART_CHEST(): EntityType;
    static get MINECART_FURNACE(): EntityType;
    static get MINECART_TNT(): EntityType;
    static get MINECART_HOPPER(): EntityType;
    static get MINECART_MOB_SPAWNER(): EntityType;
    static get CREEPER(): EntityType;
    static get SKELETON(): EntityType;
    static get SPIDER(): EntityType;
    static get GIANT(): EntityType;
    static get ZOMBIE(): EntityType;
    static get SLIME(): EntityType;
    static get GHAST(): EntityType;
    static get PIG_ZOMBIE(): EntityType;
    static get ENDERMAN(): EntityType;
    static get CAVE_SPIDER(): EntityType;
    static get SILVERFISH(): EntityType;
    static get BLAZE(): EntityType;
    static get MAGMA_CUBE(): EntityType;
    static get ENDER_DRAGON(): EntityType;
    static get WITHER(): EntityType;
    static get BAT(): EntityType;
    static get WITCH(): EntityType;
    static get ENDERMITE(): EntityType;
    static get GUARDIAN(): EntityType;
    static get SHULKER(): EntityType;
    static get PIG(): EntityType;
    static get SHEEP(): EntityType;
    static get COW(): EntityType;
    static get CHICKEN(): EntityType;
    static get SQUID(): EntityType;
    static get WOLF(): EntityType;
    static get MUSHROOM_COW(): EntityType;
    static get SNOWMAN(): EntityType;
    static get OCELOT(): EntityType;
    static get IRON_GOLEM(): EntityType;
    static get HORSE(): EntityType;
    static get RABBIT(): EntityType;
    static get POLAR_BEAR(): EntityType;
    static get LLAMA(): EntityType;
    static get LLAMA_SPIT(): EntityType;
    static get PARROT(): EntityType;
    static get VILLAGER(): EntityType;
    static get ENDER_CRYSTAL(): EntityType;
    static get TURTLE(): EntityType;
    static get PHANTOM(): EntityType;
    static get TRIDENT(): EntityType;
    static get COD(): EntityType;
    static get SALMON(): EntityType;
    static get PUFFERFISH(): EntityType;
    static get TROPICAL_FISH(): EntityType;
    static get DROWNED(): EntityType;
    static get DOLPHIN(): EntityType;
    static get CAT(): EntityType;
    static get PANDA(): EntityType;
    static get PILLAGER(): EntityType;
    static get RAVAGER(): EntityType;
    static get TRADER_LLAMA(): EntityType;
    static get WANDERING_TRADER(): EntityType;
    static get FOX(): EntityType;
    static get BEE(): EntityType;
    static get FISHING_HOOK(): EntityType;
    static get LIGHTNING(): EntityType;
    static get PLAYER(): EntityType;
    static get UNKNOWN(): EntityType;
}
