import Color from '../../../../org/bukkit/Color.js';
import Configuration from '../../../../org/bukkit/configuration/Configuration.js';
import ConfigurationOptions from '../../../../org/bukkit/configuration/ConfigurationOptions.js';
import ConfigurationSection from '../../../../org/bukkit/configuration/ConfigurationSection.js';
import ConfigurationSerializable from '../../../../org/bukkit/configuration/serialization/ConfigurationSerializable.js';
import File from '../../../../java/io/File.js';
import FileConfigurationOptions from '../../../../org/bukkit/configuration/file/FileConfigurationOptions.js';
import ItemStack from '../../../../org/bukkit/inventory/ItemStack.js';
import Location from '../../../../org/bukkit/Location.js';
import MemoryConfiguration from '../../../../org/bukkit/configuration/MemoryConfiguration.js';
import MemoryConfigurationOptions from '../../../../org/bukkit/configuration/MemoryConfigurationOptions.js';
import OfflinePlayer from '../../../../org/bukkit/OfflinePlayer.js';
import Reader from '../../../../java/io/Reader.js';
import Vector from '../../../../org/bukkit/util/Vector.js';
export default interface FileConfiguration extends MemoryConfiguration {
    load(reader: Reader): void;
    load(file: File): void;
    load(file: string): void;
    save(file: File): void;
    save(file: string): void;
    options(): FileConfigurationOptions;
    options(): MemoryConfigurationOptions;
    options(): ConfigurationOptions;
    loadFromString(arg0: string): void;
    saveToString(): string;
    getParent(): ConfigurationSection;
    setDefaults(defaults: Configuration): void;
    addDefault(path: string, value: any): void;
    getDefaults(): Configuration;
    addDefaults(defaults: Configuration): void;
    addDefaults(defaults: any): void;
    get(path: string, def: any): any;
    get(path: string): any;
    getObject(path: string, clazz: any): any;
    getObject(path: string, clazz: any, def: any): any;
    getBoolean(path: string): boolean;
    getBoolean(path: string, def: boolean): boolean;
    getInt(path: string): number;
    getInt(path: string, def: number): number;
    getLong(path: string): number;
    getLong(path: string, def: number): number;
    getDouble(path: string, def: number): number;
    getDouble(path: string): number;
    getName(): string;
    contains(path: string, ignoreDefault: boolean): boolean;
    contains(path: string): boolean;
    set(path: string, value: any): void;
    getLocation(path: string, def: Location): Location;
    getLocation(path: string): Location;
    isSet(path: string): boolean;
    getRoot(): Configuration;
    getKeys(deep: boolean): any;
    getString(path: string): string;
    getString(path: string, def: string): string;
    getFloatList(path: string): Array<number>;
    isBoolean(path: string): boolean;
    isString(path: string): boolean;
    getOfflinePlayer(path: string): OfflinePlayer;
    getOfflinePlayer(path: string, def: OfflinePlayer): OfflinePlayer;
    getStringList(path: string): Array<string>;
    getIntegerList(path: string): Array<any>;
    getBooleanList(path: string): Array<boolean>;
    getValues(deep: boolean): any;
    getCurrentPath(): string;
    createSection(path: string, map: any): ConfigurationSection;
    createSection(path: string): ConfigurationSection;
    isInt(path: string): boolean;
    isDouble(path: string): boolean;
    isLong(path: string): boolean;
    getList(path: string, def: Array<any>): Array<any>;
    getList(path: string): Array<any>;
    isList(path: string): boolean;
    getDoubleList(path: string): Array<number>;
    getConfigurationSection(path: string): ConfigurationSection;
    isConfigurationSection(path: string): boolean;
    isOfflinePlayer(path: string): boolean;
    getItemStack(path: string): ItemStack;
    getItemStack(path: string, def: ItemStack): ItemStack;
    getLongList(path: string): Array<number>;
    getShortList(path: string): Array<number>;
    getVector(path: string): Vector;
    getVector(path: string, def: Vector): Vector;
    getColor(path: string, def: Color): Color;
    getColor(path: string): Color;
    getDefaultSection(): ConfigurationSection;
    isVector(path: string): boolean;
    getByteList(path: string): Array<number>;
    isLocation(path: string): boolean;
    isItemStack(path: string): boolean;
    getCharacterList(path: string): Array<any>;
    isColor(path: string): boolean;
    getMapList(path: string): Array<any>;
    getSerializable(path: string, clazz: any): ConfigurationSerializable;
    getSerializable(path: string, clazz: any, def: ConfigurationSerializable): ConfigurationSerializable;
}
export default class FileConfiguration {
    static get $javaClass(): any;
    constructor();
    constructor(defaults: Configuration);
    static createPath(section: ConfigurationSection, key: string): string;
    static createPath(section: ConfigurationSection, key: string, relativeTo: ConfigurationSection): string;
}
