import { UnsafeValues } from '../../org/bukkit/UnsafeValues.js';
import { MapView } from '../../org/bukkit/map/MapView.js';
import { World } from '../../org/bukkit/World.js';
import { Messenger } from '../../org/bukkit/plugin/messaging/Messenger.js';
import { PluginManager } from '../../org/bukkit/plugin/PluginManager.js';
import { Server } from '../../org/bukkit/Server.js';
import { ConsoleCommandSender } from '../../org/bukkit/command/ConsoleCommandSender.js';
import { ScoreboardManager } from '../../org/bukkit/scoreboard/ScoreboardManager.js';
import { BukkitScheduler } from '../../org/bukkit/scheduler/BukkitScheduler.js';
import { Player } from '../../org/bukkit/entity/Player.js';
import { ItemFactory } from '../../org/bukkit/inventory/ItemFactory.js';
import { OfflinePlayer } from '../../org/bukkit/OfflinePlayer.js';
import { HelpMap } from '../../org/bukkit/help/HelpMap.js';
import { Inventory } from '../../org/bukkit/inventory/Inventory.js';
import { InventoryHolder } from '../../org/bukkit/inventory/InventoryHolder.js';
import { InventoryType } from '../../org/bukkit/event/inventory/InventoryType.js';
import { BanList } from '../../org/bukkit/BanList.js';
import { BanList$Type } from '../../org/bukkit/BanList$Type.js';
import { GameMode } from '../../org/bukkit/GameMode.js';
import { Recipe } from '../../org/bukkit/inventory/Recipe.js';
import { WorldCreator } from '../../org/bukkit/WorldCreator.js';
import { CommandSender } from '../../org/bukkit/command/CommandSender.js';
import { ItemStack } from '../../org/bukkit/inventory/ItemStack.js';
import { Location } from '../../org/bukkit/Location.js';
import { StructureType } from '../../org/bukkit/StructureType.js';
import { ServicesManager } from '../../org/bukkit/plugin/ServicesManager.js';
import { PluginCommand } from '../../org/bukkit/command/PluginCommand.js';
import { ChunkGenerator$ChunkData } from '../../org/bukkit/generator/ChunkGenerator$ChunkData.js';
import { Merchant } from '../../org/bukkit/inventory/Merchant.js';
import { CachedServerIcon } from '../../org/bukkit/util/CachedServerIcon.js';
import { Tag } from '../../org/bukkit/Tag.js';
import { NamespacedKey } from '../../org/bukkit/NamespacedKey.js';
import { Warning$WarningState } from '../../org/bukkit/Warning$WarningState.js';
import { BossBar } from '../../org/bukkit/boss/BossBar.js';
import { BarColor } from '../../org/bukkit/boss/BarColor.js';
import { BarStyle } from '../../org/bukkit/boss/BarStyle.js';
import { BarFlag } from '../../org/bukkit/boss/BarFlag.js';
import { KeyedBossBar } from '../../org/bukkit/boss/KeyedBossBar.js';
import { LootTable } from '../../org/bukkit/loot/LootTable.js';
import { BlockData } from '../../org/bukkit/block/data/BlockData.js';
import { Material } from '../../org/bukkit/Material.js';
import { Entity } from '../../org/bukkit/entity/Entity.js';
import { Advancement } from '../../org/bukkit/advancement/Advancement.js';
export interface Bukkit {
}
export declare class Bukkit {
    static get $javaClass(): any;
    static shutdown(): void;
    static getName(): string;
    static getUnsafe(): UnsafeValues;
    static getLogger(): any;
    static getPort(): number;
    static getMap(id: number): MapView;
    static createMap(world: World): MapView;
    static getVersion(): string;
    static getMessenger(): Messenger;
    static getPluginManager(): PluginManager;
    static getServer(): Server;
    static getOnlinePlayers(): any;
    static getWorld(_name: string): World;
    static getWorld(uid: string): World;
    static getConsoleSender(): ConsoleCommandSender;
    static getAllowFlight(): boolean;
    static getMonsterSpawnLimit(): number;
    static getTicksPerMonsterSpawns(): number;
    static getWaterAnimalSpawnLimit(): number;
    static getGenerateStructures(): boolean;
    static getWhitelistedPlayers(): any;
    static getConnectionThrottle(): number;
    static getScoreboardManager(): ScoreboardManager;
    static getAnimalSpawnLimit(): number;
    static getAmbientSpawnLimit(): number;
    static getUpdateFolderFile(): any;
    static getTicksPerAnimalSpawns(): number;
    static advancementIterator(): any;
    static getScheduler(): BukkitScheduler;
    static getPlayer(id: string): Player;
    static getPlayer(_name: string): Player;
    static getItemFactory(): ItemFactory;
    static unbanIP(address: string): void;
    static getOperators(): any;
    static getWorldContainer(): any;
    static getOfflinePlayers(): Array<OfflinePlayer>;
    static getHelpMap(): HelpMap;
    static reloadWhitelist(): void;
    static savePlayers(): void;
    static getPlayerExact(_name: string): Player;
    static createInventory(owner: InventoryHolder, type: InventoryType, title: string): Inventory;
    static createInventory(owner: InventoryHolder, size: number): Inventory;
    static createInventory(owner: InventoryHolder, type: InventoryType): Inventory;
    static createInventory(owner: InventoryHolder, size: number, title: string): Inventory;
    static getBukkitVersion(): string;
    static getAllowEnd(): boolean;
    static recipeIterator(): any;
    static reload(): void;
    static getOnlineMode(): boolean;
    static broadcast(message: string, permission: string): number;
    static getIPBans(): any;
    static getBanList(type: BanList$Type): BanList;
    static getIp(): string;
    static setSpawnRadius(value: number): void;
    static setWhitelist(value: boolean): void;
    static getDefaultGameMode(): GameMode;
    static clearRecipes(): void;
    static getWorldType(): string;
    static getWorlds(): any;
    static addRecipe(recipe: Recipe): boolean;
    static getViewDistance(): number;
    static getSpawnRadius(): number;
    static hasWhitelist(): boolean;
    static broadcastMessage(message: string): number;
    static createWorld(creator: WorldCreator): World;
    static resetRecipes(): void;
    static dispatchCommand(sender: CommandSender, commandLine: string): boolean;
    static matchPlayer(_name: string): any;
    static getOfflinePlayer(_name: string): OfflinePlayer;
    static getOfflinePlayer(id: string): OfflinePlayer;
    static getCommandAliases(): any;
    static createExplorerMap(world: World, location: Location, structureType: StructureType, radius: number, findUnexplored: boolean): ItemStack;
    static createExplorerMap(world: World, location: Location, structureType: StructureType): ItemStack;
    static getUpdateFolder(): string;
    static getBannedPlayers(): any;
    static setDefaultGameMode(mode: GameMode): void;
    static getMaxPlayers(): number;
    static getServicesManager(): ServicesManager;
    static getAllowNether(): boolean;
    static unloadWorld(_name: string, save: boolean): boolean;
    static unloadWorld(world: World, save: boolean): boolean;
    static reloadData(): void;
    static getRecipesFor(result: ItemStack): any;
    static isHardcore(): boolean;
    static banIP(address: string): void;
    static getPluginCommand(_name: string): PluginCommand;
    static createChunkData(world: World): ChunkGenerator$ChunkData;
    static createMerchant(title: string): Merchant;
    static loadServerIcon(file: any): CachedServerIcon;
    static loadServerIcon(image: any): CachedServerIcon;
    static getTag(registry: string, tag: NamespacedKey, clazz: any): Tag;
    static getServerIcon(): CachedServerIcon;
    static removeBossBar(key: NamespacedKey): boolean;
    static setIdleTimeout(threshold: number): void;
    static getWarningState(): Warning$WarningState;
    static getIdleTimeout(): number;
    static createBossBar(title: string, color: BarColor, style: BarStyle, flags: Array<BarFlag>): BossBar;
    static createBossBar(key: NamespacedKey, title: string, color: BarColor, style: BarStyle, flags: Array<BarFlag>): KeyedBossBar;
    static getShutdownMessage(): string;
    static getLootTable(key: NamespacedKey): LootTable;
    static getMotd(): string;
    static isPrimaryThread(): boolean;
    static createBlockData(material: Material, consumer: any): BlockData;
    static createBlockData(data: string): BlockData;
    static createBlockData(material: Material, data: string): BlockData;
    static createBlockData(material: Material): BlockData;
    static getBossBars(): any;
    static getBossBar(key: NamespacedKey): KeyedBossBar;
    static getEntity(uuid: string): Entity;
    static getTags(registry: string, clazz: any): any;
    static selectEntities(sender: CommandSender, selector: string): any;
    static getAdvancement(key: NamespacedKey): Advancement;
    static setServer(server: Server): void;
}
