import Block from '../../org/bukkit/block/Block.js';
import Chunk from '../../org/bukkit/Chunk.js';
import ConfigurationSerializable from '../../org/bukkit/configuration/serialization/ConfigurationSerializable.js';
import Vector from '../../org/bukkit/util/Vector.js';
import World from '../../org/bukkit/World.js';
export default interface Location extends ConfigurationSerializable {
    getBlock(): Block;
    getWorld(): World;
    serialize(): any;
    getChunk(): Chunk;
    setX(x: number): void;
    getX(): number;
    getBlockX(): number;
    setY(y: number): void;
    getY(): number;
    getBlockY(): number;
    setZ(z: number): void;
    getZ(): number;
    getBlockZ(): number;
    setYaw(yaw: number): void;
    getYaw(): number;
    setPitch(pitch: number): void;
    getPitch(): number;
    getDirection(): Vector;
    setDirection(vector: Vector): Location;
    subtract(vec: Vector): Location;
    subtract(vec: Location): Location;
    subtract(x: number, y: number, z: number): Location;
    lengthSquared(): number;
    distance(o: Location): number;
    distanceSquared(o: Location): number;
    multiply(m: number): Location;
    toVector(): Vector;
    checkFinite(): void;
    setWorld(world: World): void;
    isWorldLoaded(): boolean;
    add(vec: Location): Location;
    add(vec: Vector): Location;
    add(x: number, y: number, z: number): Location;
    clone(): Location;
    clone(): any;
    length(): number;
    zero(): Location;
}
export default class Location {
    static get $javaClass(): any;
    constructor(world: World, x: number, y: number, z: number, yaw: number, pitch: number);
    constructor(world: World, x: number, y: number, z: number);
    static deserialize(args: any): Location;
    static locToBlock(loc: number): number;
    static normalizeYaw(yaw: number): number;
    static normalizePitch(pitch: number): number;
}
