import Advancement from '../../org/bukkit/advancement/Advancement.js';
import BanList from '../../org/bukkit/BanList.js';
import BanList$Type from '../../org/bukkit/BanList$Type.js';
import BarColor from '../../org/bukkit/boss/BarColor.js';
import BarFlag from '../../org/bukkit/boss/BarFlag.js';
import BarStyle from '../../org/bukkit/boss/BarStyle.js';
import BlockData from '../../org/bukkit/block/data/BlockData.js';
import BossBar from '../../org/bukkit/boss/BossBar.js';
import BukkitScheduler from '../../org/bukkit/scheduler/BukkitScheduler.js';
import CachedServerIcon from '../../org/bukkit/util/CachedServerIcon.js';
import ChunkGenerator$ChunkData from '../../org/bukkit/generator/ChunkGenerator$ChunkData.js';
import CommandSender from '../../org/bukkit/command/CommandSender.js';
import ConsoleCommandSender from '../../org/bukkit/command/ConsoleCommandSender.js';
import Entity from '../../org/bukkit/entity/Entity.js';
import File from '../../java/io/File.js';
import GameMode from '../../org/bukkit/GameMode.js';
import HelpMap from '../../org/bukkit/help/HelpMap.js';
import Inventory from '../../org/bukkit/inventory/Inventory.js';
import InventoryHolder from '../../org/bukkit/inventory/InventoryHolder.js';
import InventoryType from '../../org/bukkit/event/inventory/InventoryType.js';
import ItemFactory from '../../org/bukkit/inventory/ItemFactory.js';
import ItemStack from '../../org/bukkit/inventory/ItemStack.js';
import KeyedBossBar from '../../org/bukkit/boss/KeyedBossBar.js';
import Location from '../../org/bukkit/Location.js';
import LootTable from '../../org/bukkit/loot/LootTable.js';
import MapView from '../../org/bukkit/map/MapView.js';
import Material from '../../org/bukkit/Material.js';
import Merchant from '../../org/bukkit/inventory/Merchant.js';
import Messenger from '../../org/bukkit/plugin/messaging/Messenger.js';
import NamespacedKey from '../../org/bukkit/NamespacedKey.js';
import OfflinePlayer from '../../org/bukkit/OfflinePlayer.js';
import Player from '../../org/bukkit/entity/Player.js';
import Plugin from '../../org/bukkit/plugin/Plugin.js';
import PluginCommand from '../../org/bukkit/command/PluginCommand.js';
import PluginManager from '../../org/bukkit/plugin/PluginManager.js';
import PluginMessageRecipient from '../../org/bukkit/plugin/messaging/PluginMessageRecipient.js';
import Recipe from '../../org/bukkit/inventory/Recipe.js';
import ScoreboardManager from '../../org/bukkit/scoreboard/ScoreboardManager.js';
import ServicesManager from '../../org/bukkit/plugin/ServicesManager.js';
import StructureType from '../../org/bukkit/StructureType.js';
import Tag from '../../org/bukkit/Tag.js';
import UnsafeValues from '../../org/bukkit/UnsafeValues.js';
import Warning$WarningState from '../../org/bukkit/Warning$WarningState.js';
import World from '../../org/bukkit/World.js';
import WorldCreator from '../../org/bukkit/WorldCreator.js';
export default interface Server extends PluginMessageRecipient {
    shutdown(): void;
    getName(): string;
    getUnsafe(): UnsafeValues;
    getLogger(): any;
    getPort(): number;
    getMap(arg0: number): MapView;
    createMap(arg0: World): MapView;
    getVersion(): string;
    getServicesManager(): ServicesManager;
    getPluginManager(): PluginManager;
    getMessenger(): Messenger;
    getItemFactory(): ItemFactory;
    getScheduler(): BukkitScheduler;
    getWorld(arg0: string): World;
    getWorld(arg0: string): World;
    getAllowFlight(): boolean;
    selectEntities(arg0: CommandSender, arg1: string): Array<Entity>;
    getBossBars(): any;
    getAdvancement(arg0: NamespacedKey): Advancement;
    createChunkData(arg0: World): ChunkGenerator$ChunkData;
    getTag(arg0: string, arg1: NamespacedKey, arg2: any): Tag;
    createBlockData(arg0: Material, arg1: string): BlockData;
    createBlockData(arg0: string): BlockData;
    createBlockData(arg0: Material, arg1: any): BlockData;
    createBlockData(arg0: Material): BlockData;
    getTags(arg0: string, arg1: any): any;
    createBossBar(arg0: string, arg1: BarColor, arg2: BarStyle, arg3: Array<BarFlag>): BossBar;
    createBossBar(arg0: NamespacedKey, arg1: string, arg2: BarColor, arg3: BarStyle, arg4: Array<BarFlag>): KeyedBossBar;
    getBossBar(arg0: NamespacedKey): KeyedBossBar;
    removeBossBar(arg0: NamespacedKey): boolean;
    getLootTable(arg0: NamespacedKey): LootTable;
    getEntity(arg0: string): Entity;
    getPlayer(arg0: string): Player;
    getPlayer(arg0: string): Player;
    getAllowNether(): boolean;
    getWorldContainer(): File;
    getOfflinePlayers(): Array<OfflinePlayer>;
    getPluginCommand(arg0: string): PluginCommand;
    setWhitelist(arg0: boolean): void;
    savePlayers(): void;
    getSpawnRadius(): number;
    getOnlinePlayers(): any;
    reload(): void;
    getPlayerExact(arg0: string): Player;
    addRecipe(arg0: Recipe): boolean;
    getOnlineMode(): boolean;
    createExplorerMap(arg0: World, arg1: Location, arg2: StructureType): ItemStack;
    createExplorerMap(arg0: World, arg1: Location, arg2: StructureType, arg3: number, arg4: boolean): ItemStack;
    recipeIterator(): any;
    getCommandAliases(): any;
    setSpawnRadius(arg0: number): void;
    isHardcore(): boolean;
    getAllowEnd(): boolean;
    getBukkitVersion(): string;
    getOfflinePlayer(arg0: string): OfflinePlayer;
    getOfflinePlayer(arg0: string): OfflinePlayer;
    getIPBans(): any;
    getOperators(): any;
    setDefaultGameMode(arg0: GameMode): void;
    getUpdateFolder(): string;
    createInventory(arg0: InventoryHolder, arg1: number, arg2: string): Inventory;
    createInventory(arg0: InventoryHolder, arg1: number): Inventory;
    createInventory(arg0: InventoryHolder, arg1: InventoryType, arg2: string): Inventory;
    createInventory(arg0: InventoryHolder, arg1: InventoryType): Inventory;
    createMerchant(arg0: string): Merchant;
    unbanIP(arg0: string): void;
    getRecipesFor(arg0: ItemStack): Array<Recipe>;
    createWorld(arg0: WorldCreator): World;
    clearRecipes(): void;
    getBanList(arg0: BanList$Type): BanList;
    getHelpMap(): HelpMap;
    isPrimaryThread(): boolean;
    getMotd(): string;
    getShutdownMessage(): string;
    getServerIcon(): CachedServerIcon;
    getIdleTimeout(): number;
    banIP(arg0: string): void;
    broadcastMessage(arg0: string): number;
    reloadWhitelist(): void;
    getIp(): string;
    dispatchCommand(arg0: CommandSender, arg1: string): boolean;
    resetRecipes(): void;
    getViewDistance(): number;
    removeRecipe(arg0: NamespacedKey): boolean;
    getDefaultGameMode(): GameMode;
    getWorlds(): Array<World>;
    broadcast(arg0: string, arg1: string): number;
    getWorldType(): string;
    matchPlayer(arg0: string): Array<Player>;
    getConsoleSender(): ConsoleCommandSender;
    loadServerIcon(arg0: any): CachedServerIcon;
    loadServerIcon(arg0: File): CachedServerIcon;
    setIdleTimeout(arg0: number): void;
    getMaxPlayers(): number;
    unloadWorld(arg0: string, arg1: boolean): boolean;
    unloadWorld(arg0: World, arg1: boolean): boolean;
    getWarningState(): Warning$WarningState;
    hasWhitelist(): boolean;
    reloadData(): void;
    getBannedPlayers(): any;
    getTicksPerAnimalSpawns(): number;
    getGenerateStructures(): boolean;
    getWhitelistedPlayers(): any;
    getScoreboardManager(): ScoreboardManager;
    getConnectionThrottle(): number;
    advancementIterator(): any;
    getUpdateFolderFile(): File;
    getTicksPerMonsterSpawns(): number;
    getWaterAnimalSpawnLimit(): number;
    getAmbientSpawnLimit(): number;
    getAnimalSpawnLimit(): number;
    getMonsterSpawnLimit(): number;
    getListeningPluginChannels(): any;
    sendPluginMessage(arg0: Plugin, arg1: string, arg2: Array<number>): void;
}
export default class Server {
    static get $javaClass(): any;
    static get BROADCAST_CHANNEL_ADMINISTRATIVE(): string;
    static get BROADCAST_CHANNEL_USERS(): string;
}
