import { Keyed } from '../../org/bukkit/Keyed.js';
import { NamespacedKey } from '../../org/bukkit/NamespacedKey.js';
export interface Tag extends Keyed {
    getValues(): any;
    isTagged(arg0: Keyed): boolean;
    getKey(): NamespacedKey;
}
export declare class Tag {
    static get $javaClass(): any;
    static get REGISTRY_BLOCKS(): string;
    static get WOOL(): Tag;
    static get PLANKS(): Tag;
    static get STONE_BRICKS(): Tag;
    static get WOODEN_BUTTONS(): Tag;
    static get BUTTONS(): Tag;
    static get CARPETS(): Tag;
    static get WOODEN_DOORS(): Tag;
    static get WOODEN_STAIRS(): Tag;
    static get WOODEN_SLABS(): Tag;
    static get WOODEN_FENCES(): Tag;
    static get WOODEN_PRESSURE_PLATES(): Tag;
    static get WOODEN_TRAPDOORS(): Tag;
    static get DOORS(): Tag;
    static get SAPLINGS(): Tag;
    static get LOGS(): Tag;
    static get DARK_OAK_LOGS(): Tag;
    static get OAK_LOGS(): Tag;
    static get BIRCH_LOGS(): Tag;
    static get ACACIA_LOGS(): Tag;
    static get JUNGLE_LOGS(): Tag;
    static get SPRUCE_LOGS(): Tag;
    static get BANNERS(): Tag;
    static get SAND(): Tag;
    static get STAIRS(): Tag;
    static get SLABS(): Tag;
    static get WALLS(): Tag;
    static get ANVIL(): Tag;
    static get RAILS(): Tag;
    static get LEAVES(): Tag;
    static get TRAPDOORS(): Tag;
    static get FLOWER_POTS(): Tag;
    static get SMALL_FLOWERS(): Tag;
    static get BEDS(): Tag;
    static get FENCES(): Tag;
    static get TALL_FLOWERS(): Tag;
    static get FLOWERS(): Tag;
    static get SHULKER_BOXES(): Tag;
    static get ENDERMAN_HOLDABLE(): Tag;
    static get ICE(): Tag;
    static get VALID_SPAWN(): Tag;
    static get IMPERMEABLE(): Tag;
    static get UNDERWATER_BONEMEALS(): Tag;
    static get CORAL_BLOCKS(): Tag;
    static get WALL_CORALS(): Tag;
    static get CORAL_PLANTS(): Tag;
    static get CORALS(): Tag;
    static get BAMBOO_PLANTABLE_ON(): Tag;
    static get STANDING_SIGNS(): Tag;
    static get WALL_SIGNS(): Tag;
    static get SIGNS(): Tag;
    static get DRAGON_IMMUNE(): Tag;
    static get WITHER_IMMUNE(): Tag;
    static get BEEHIVES(): Tag;
    static get CROPS(): Tag;
    static get BEE_GROWABLES(): Tag;
    static get PORTALS(): Tag;
    static get REGISTRY_ITEMS(): string;
    static get ITEMS_BANNERS(): Tag;
    static get ITEMS_BOATS(): Tag;
    static get ITEMS_FISHES(): Tag;
    static get ITEMS_MUSIC_DISCS(): Tag;
    static get ITEMS_COALS(): Tag;
    static get ITEMS_ARROWS(): Tag;
    static get ITEMS_LECTERN_BOOKS(): Tag;
}
