export default interface BukkitObjectInputStream {
    readFloat(): number;
    readFully(arg0: Array<number>, arg1: number, arg2: number): void;
    readFully(arg0: Array<number>): void;
    readLong(): number;
    readByte(): number;
    readUnshared(): any;
    registerValidation(arg0: any, arg1: number): void;
    readUnsignedShort(): number;
    skipBytes(arg0: number): number;
    readBoolean(): boolean;
    readUnsignedByte(): number;
    readShort(): number;
    readDouble(): number;
    readObject(): any;
    defaultReadObject(): void;
    read(arg0: Array<number>, arg1: number, arg2: number): number;
    read(): number;
    readLine(): string;
    close(): void;
    readInt(): number;
    readFields(): any;
    available(): number;
    readChar(): string;
    readUTF(): string;
    read(arg0: Array<number>): number;
    mark(arg0: number): void;
    skip(arg0: number): number;
    markSupported(): boolean;
    reset(): void;
}
export default class BukkitObjectInputStream {
    static get $javaClass(): any;
    constructor(_in: any);
    static get STREAM_MAGIC(): number;
    static get STREAM_VERSION(): number;
    static get TC_BASE(): number;
    static get TC_NULL(): number;
    static get TC_REFERENCE(): number;
    static get TC_CLASSDESC(): number;
    static get TC_OBJECT(): number;
    static get TC_STRING(): number;
    static get TC_ARRAY(): number;
    static get TC_CLASS(): number;
    static get TC_BLOCKDATA(): number;
    static get TC_ENDBLOCKDATA(): number;
    static get TC_RESET(): number;
    static get TC_BLOCKDATALONG(): number;
    static get TC_EXCEPTION(): number;
    static get TC_LONGSTRING(): number;
    static get TC_PROXYCLASSDESC(): number;
    static get TC_ENUM(): number;
    static get TC_MAX(): number;
    static get baseWireHandle(): number;
    static get SC_WRITE_METHOD(): number;
    static get SC_BLOCK_DATA(): number;
    static get SC_SERIALIZABLE(): number;
    static get SC_EXTERNALIZABLE(): number;
    static get SC_ENUM(): number;
    static get SUBSTITUTION_PERMISSION(): any;
    static get SUBCLASS_IMPLEMENTATION_PERMISSION(): any;
    static get PROTOCOL_VERSION_1(): number;
    static get PROTOCOL_VERSION_2(): number;
}
