import InputStream from '../../../../java/io/InputStream.js';
import ObjectInputFilter from '../../../../java/io/ObjectInputFilter.js';
import ObjectInputStream from '../../../../java/io/ObjectInputStream.js';
import ObjectInputStream$GetField from '../../../../java/io/ObjectInputStream$GetField.js';
import ObjectInputValidation from '../../../../java/io/ObjectInputValidation.js';
import OutputStream from '../../../../java/io/OutputStream.js';
import SerializablePermission from '../../../../java/io/SerializablePermission.js';
export default interface BukkitObjectInputStream extends ObjectInputStream {
    readObject(): any;
    defaultReadObject(): void;
    read(): number;
    read(buf: Array<number>, off: number, len: number): number;
    readLine(): string;
    close(): void;
    readInt(): number;
    readFields(): ObjectInputStream$GetField;
    available(): number;
    readUTF(): string;
    readFloat(): number;
    readFully(buf: Array<number>, off: number, len: number): void;
    readFully(buf: Array<number>): void;
    readChar(): string;
    skipBytes(len: number): number;
    readBoolean(): boolean;
    readByte(): number;
    readUnsignedByte(): number;
    readShort(): number;
    readUnsignedShort(): number;
    readLong(): number;
    readDouble(): number;
    readUnshared(): any;
    registerValidation(obj: ObjectInputValidation, prio: number): void;
    getObjectInputFilter(): ObjectInputFilter;
    setObjectInputFilter(filter: ObjectInputFilter): void;
    read(b: Array<number>): number;
    mark(readlimit: number): void;
    readAllBytes(): Array<number>;
    readNBytes(b: Array<number>, off: number, len: number): number;
    readNBytes(len: number): Array<number>;
    transferTo(out: OutputStream): number;
    skip(n: number): number;
    markSupported(): boolean;
    reset(): void;
}
export default class BukkitObjectInputStream {
    static get $javaClass(): any;
    constructor(_in: InputStream);
    static get STREAM_MAGIC(): number;
    static get STREAM_VERSION(): number;
    static get TC_BASE(): number;
    static get TC_NULL(): number;
    static get TC_REFERENCE(): number;
    static get TC_CLASSDESC(): number;
    static get TC_OBJECT(): number;
    static get TC_STRING(): number;
    static get TC_ARRAY(): number;
    static get TC_CLASS(): number;
    static get TC_BLOCKDATA(): number;
    static get TC_ENDBLOCKDATA(): number;
    static get TC_RESET(): number;
    static get TC_BLOCKDATALONG(): number;
    static get TC_EXCEPTION(): number;
    static get TC_LONGSTRING(): number;
    static get TC_PROXYCLASSDESC(): number;
    static get TC_ENUM(): number;
    static get TC_MAX(): number;
    static get baseWireHandle(): number;
    static get SC_WRITE_METHOD(): number;
    static get SC_BLOCK_DATA(): number;
    static get SC_SERIALIZABLE(): number;
    static get SC_EXTERNALIZABLE(): number;
    static get SC_ENUM(): number;
    static get SUBSTITUTION_PERMISSION(): SerializablePermission;
    static get SUBCLASS_IMPLEMENTATION_PERMISSION(): SerializablePermission;
    static get SERIAL_FILTER_PERMISSION(): SerializablePermission;
    static get PROTOCOL_VERSION_1(): number;
    static get PROTOCOL_VERSION_2(): number;
    static nullInputStream(): InputStream;
}
