import { Vector } from '../../../org/bukkit/util/Vector.js';
import { Location } from '../../../org/bukkit/Location.js';
import { World } from '../../../org/bukkit/World.js';
export interface BlockVector extends Vector {
    clone(): Vector;
    clone(): any;
    clone(): BlockVector;
    add(vec: Vector): Vector;
    length(): number;
    dot(other: Vector): number;
    copy(vec: Vector): Vector;
    zero(): Vector;
    normalize(): Vector;
    distance(o: Vector): number;
    divide(vec: Vector): Vector;
    multiply(vec: Vector): Vector;
    multiply(m: number): Vector;
    multiply(m: number): Vector;
    multiply(m: number): Vector;
    isNormalized(): boolean;
    serialize(): any;
    getX(): number;
    getY(): number;
    getBlockZ(): number;
    subtract(vec: Vector): Vector;
    getZ(): number;
    checkFinite(): void;
    setX(x: number): Vector;
    setX(x: number): Vector;
    setX(x: number): Vector;
    lengthSquared(): number;
    getBlockX(): number;
    setZ(z: number): Vector;
    setZ(z: number): Vector;
    setZ(z: number): Vector;
    distanceSquared(o: Vector): number;
    setY(y: number): Vector;
    setY(y: number): Vector;
    setY(y: number): Vector;
    getBlockY(): number;
    rotateAroundNonUnitAxis(axis: Vector, angle: number): Vector;
    midpoint(other: Vector): Vector;
    getMidpoint(other: Vector): Vector;
    crossProduct(o: Vector): Vector;
    angle(other: Vector): number;
    getCrossProduct(o: Vector): Vector;
    isInSphere(origin: Vector, radius: number): boolean;
    isInAABB(min: Vector, max: Vector): boolean;
    rotateAroundY(angle: number): Vector;
    rotateAroundZ(angle: number): Vector;
    rotateAroundX(angle: number): Vector;
    toLocation(world: World): Location;
    toLocation(world: World, yaw: number, pitch: number): Location;
    toBlockVector(): BlockVector;
    rotateAroundAxis(axis: Vector, angle: number): Vector;
}
export declare class BlockVector {
    static get $javaClass(): any;
    constructor(x: number, y: number, z: number);
    constructor(x: number, y: number, z: number);
    constructor(x: number, y: number, z: number);
    constructor(vec: Vector);
    constructor();
    static deserialize(args: any): BlockVector;
    static deserialize(args: any): Vector;
    static getMaximum(v1: Vector, v2: Vector): Vector;
    static getMinimum(v1: Vector, v2: Vector): Vector;
    static getRandom(): Vector;
    static getEpsilon(): number;
}
