import { Ref } from '../../java/sql/Ref.js';
import { Date } from '../../java/sql/Date.js';
import { Timestamp } from '../../java/sql/Timestamp.js';
import { Time } from '../../java/sql/Time.js';
import { _Array } from '../../java/sql/Array.js';
import { SQLType } from '../../java/sql/SQLType.js';
import { RowId } from '../../java/sql/RowId.js';
import { NClob } from '../../java/sql/NClob.js';
import { SQLXML } from '../../java/sql/SQLXML.js';
import { Blob } from '../../java/sql/Blob.js';
import { Clob } from '../../java/sql/Clob.js';
import { ParameterMetaData } from '../../java/sql/ParameterMetaData.js';
import { ResultSet } from '../../java/sql/ResultSet.js';
import { ResultSetMetaData } from '../../java/sql/ResultSetMetaData.js';
import { Connection } from '../../java/sql/Connection.js';
import { SQLWarning } from '../../java/sql/SQLWarning.js';
export interface CallableStatement {
    getObject(arg0: string, arg1: any): any;
    getObject(arg0: string): any;
    getObject(arg0: string, arg1: any): any;
    getObject(arg0: number, arg1: any): any;
    getObject(arg0: number, arg1: any): any;
    getObject(arg0: number): any;
    getBoolean(arg0: string): boolean;
    getBoolean(arg0: number): boolean;
    getByte(arg0: string): number;
    getByte(arg0: number): number;
    getShort(arg0: number): number;
    getShort(arg0: string): number;
    getInt(arg0: string): number;
    getInt(arg0: number): number;
    getLong(arg0: string): number;
    getLong(arg0: number): number;
    getFloat(arg0: string): number;
    getFloat(arg0: number): number;
    getDouble(arg0: string): number;
    getDouble(arg0: number): number;
    getBytes(arg0: string): Array<number>;
    getBytes(arg0: number): Array<number>;
    setBoolean(arg0: string, arg1: boolean): void;
    setByte(arg0: string, arg1: number): void;
    setShort(arg0: string, arg1: number): void;
    setInt(arg0: string, arg1: number): void;
    setLong(arg0: string, arg1: number): void;
    setFloat(arg0: string, arg1: number): void;
    setDouble(arg0: string, arg1: number): void;
    getRef(arg0: string): Ref;
    getRef(arg0: number): Ref;
    getDate(arg0: number, arg1: any): Date;
    getDate(arg0: number): Date;
    getDate(arg0: string): Date;
    getDate(arg0: string, arg1: any): Date;
    setTimestamp(arg0: string, arg1: Timestamp, arg2: any): void;
    setTimestamp(arg0: string, arg1: Timestamp): void;
    getTime(arg0: string, arg1: any): Time;
    getTime(arg0: string): Time;
    getTime(arg0: number): Time;
    getTime(arg0: number, arg1: any): Time;
    setTime(arg0: string, arg1: Time): void;
    setTime(arg0: string, arg1: Time, arg2: any): void;
    getString(arg0: string): string;
    getString(arg0: number): string;
    getURL(arg0: string): any;
    getURL(arg0: number): any;
    setURL(arg0: string, arg1: any): void;
    getArray(arg0: number): _Array;
    getArray(arg0: string): _Array;
    setDate(arg0: string, arg1: Date, arg2: any): void;
    setDate(arg0: string, arg1: Date): void;
    setNCharacterStream(arg0: string, arg1: any): void;
    setNCharacterStream(arg0: string, arg1: any, arg2: number): void;
    getNCharacterStream(arg0: string): any;
    getNCharacterStream(arg0: number): any;
    registerOutParameter(parameterName: string, sqlType: SQLType, typeName: string): void;
    registerOutParameter(parameterIndex: number, sqlType: SQLType, scale: number): void;
    registerOutParameter(parameterIndex: number, sqlType: SQLType, typeName: string): void;
    registerOutParameter(parameterName: string, sqlType: SQLType, scale: number): void;
    registerOutParameter(parameterIndex: number, sqlType: SQLType): void;
    registerOutParameter(parameterName: string, sqlType: SQLType): void;
    registerOutParameter(arg0: string, arg1: number, arg2: string): void;
    registerOutParameter(arg0: number, arg1: number, arg2: number): void;
    registerOutParameter(arg0: string, arg1: number, arg2: number): void;
    registerOutParameter(arg0: string, arg1: number): void;
    registerOutParameter(arg0: number, arg1: number, arg2: string): void;
    registerOutParameter(arg0: number, arg1: number): void;
    setRowId(arg0: string, arg1: RowId): void;
    setNString(arg0: string, arg1: string): void;
    setNClob(arg0: string, arg1: any, arg2: number): void;
    setNClob(arg0: string, arg1: NClob): void;
    setNClob(arg0: string, arg1: any): void;
    setSQLXML(arg0: string, arg1: SQLXML): void;
    setAsciiStream(arg0: string, arg1: any): void;
    setAsciiStream(arg0: string, arg1: any, arg2: number): void;
    setAsciiStream(arg0: string, arg1: any, arg2: number): void;
    setBigDecimal(arg0: string, arg1: any): void;
    setString(arg0: string, arg1: string): void;
    setBinaryStream(arg0: string, arg1: any, arg2: number): void;
    setBinaryStream(arg0: string, arg1: any): void;
    setBinaryStream(arg0: string, arg1: any, arg2: number): void;
    setCharacterStream(arg0: string, arg1: any): void;
    setCharacterStream(arg0: string, arg1: any, arg2: number): void;
    setCharacterStream(arg0: string, arg1: any, arg2: number): void;
    setBlob(arg0: string, arg1: any, arg2: number): void;
    setBlob(arg0: string, arg1: any): void;
    setBlob(arg0: string, arg1: Blob): void;
    setNull(arg0: string, arg1: number, arg2: string): void;
    setNull(arg0: string, arg1: number): void;
    setBytes(arg0: string, arg1: Array<number>): void;
    setObject(parameterName: string, x: any, targetSqlType: SQLType, scaleOrLength: number): void;
    setObject(arg0: string, arg1: any, arg2: number): void;
    setObject(parameterName: string, x: any, targetSqlType: SQLType): void;
    setObject(arg0: string, arg1: any, arg2: number, arg3: number): void;
    setObject(arg0: string, arg1: any): void;
    setClob(arg0: string, arg1: Clob): void;
    setClob(arg0: string, arg1: any, arg2: number): void;
    setClob(arg0: string, arg1: any): void;
    getTimestamp(arg0: string, arg1: any): Timestamp;
    getTimestamp(arg0: number, arg1: any): Timestamp;
    getTimestamp(arg0: string): Timestamp;
    getTimestamp(arg0: number): Timestamp;
    getBigDecimal(arg0: string): any;
    getBigDecimal(arg0: number): any;
    getBigDecimal(arg0: number, arg1: number): any;
    wasNull(): boolean;
    getCharacterStream(arg0: string): any;
    getCharacterStream(arg0: number): any;
    getBlob(arg0: string): Blob;
    getBlob(arg0: number): Blob;
    getRowId(arg0: string): RowId;
    getRowId(arg0: number): RowId;
    getClob(arg0: number): Clob;
    getClob(arg0: string): Clob;
    getNString(arg0: string): string;
    getNString(arg0: number): string;
    getNClob(arg0: string): NClob;
    getNClob(arg0: number): NClob;
    getSQLXML(arg0: string): SQLXML;
    getSQLXML(arg0: number): SQLXML;
    execute(): boolean;
    setBoolean(arg0: number, arg1: boolean): void;
    setByte(arg0: number, arg1: number): void;
    setShort(arg0: number, arg1: number): void;
    setInt(arg0: number, arg1: number): void;
    setLong(arg0: number, arg1: number): void;
    setFloat(arg0: number, arg1: number): void;
    setDouble(arg0: number, arg1: number): void;
    setTimestamp(arg0: number, arg1: Timestamp): void;
    setTimestamp(arg0: number, arg1: Timestamp, arg2: any): void;
    setTime(arg0: number, arg1: Time, arg2: any): void;
    setTime(arg0: number, arg1: Time): void;
    setURL(arg0: number, arg1: any): void;
    setArray(arg0: number, arg1: _Array): void;
    setDate(arg0: number, arg1: Date): void;
    setDate(arg0: number, arg1: Date, arg2: any): void;
    getParameterMetaData(): ParameterMetaData;
    setNCharacterStream(arg0: number, arg1: any): void;
    setNCharacterStream(arg0: number, arg1: any, arg2: number): void;
    executeQuery(): ResultSet;
    executeUpdate(): number;
    setRowId(arg0: number, arg1: RowId): void;
    setNString(arg0: number, arg1: string): void;
    setNClob(arg0: number, arg1: any, arg2: number): void;
    setNClob(arg0: number, arg1: any): void;
    setNClob(arg0: number, arg1: NClob): void;
    setSQLXML(arg0: number, arg1: SQLXML): void;
    executeLargeUpdate(): number;
    clearParameters(): void;
    setRef(arg0: number, arg1: Ref): void;
    setAsciiStream(arg0: number, arg1: any): void;
    setAsciiStream(arg0: number, arg1: any, arg2: number): void;
    setAsciiStream(arg0: number, arg1: any, arg2: number): void;
    setUnicodeStream(arg0: number, arg1: any, arg2: number): void;
    addBatch(): void;
    setBigDecimal(arg0: number, arg1: any): void;
    setString(arg0: number, arg1: string): void;
    setBinaryStream(arg0: number, arg1: any, arg2: number): void;
    setBinaryStream(arg0: number, arg1: any): void;
    setBinaryStream(arg0: number, arg1: any, arg2: number): void;
    setCharacterStream(arg0: number, arg1: any, arg2: number): void;
    setCharacterStream(arg0: number, arg1: any): void;
    setCharacterStream(arg0: number, arg1: any, arg2: number): void;
    setBlob(arg0: number, arg1: any): void;
    setBlob(arg0: number, arg1: any, arg2: number): void;
    setBlob(arg0: number, arg1: Blob): void;
    setNull(arg0: number, arg1: number, arg2: string): void;
    setNull(arg0: number, arg1: number): void;
    setBytes(arg0: number, arg1: Array<number>): void;
    setObject(arg0: number, arg1: any): void;
    setObject(arg0: number, arg1: any, arg2: number, arg3: number): void;
    setObject(arg0: number, arg1: any, arg2: number): void;
    setObject(parameterIndex: number, x: any, targetSqlType: SQLType): void;
    setObject(parameterIndex: number, x: any, targetSqlType: SQLType, scaleOrLength: number): void;
    setClob(arg0: number, arg1: any, arg2: number): void;
    setClob(arg0: number, arg1: Clob): void;
    setClob(arg0: number, arg1: any): void;
    getMetaData(): ResultSetMetaData;
    execute(arg0: string, arg1: number): boolean;
    execute(arg0: string): boolean;
    execute(arg0: string, arg1: Array<string>): boolean;
    execute(arg0: string, arg1: Array<number>): boolean;
    close(): void;
    getResultSetConcurrency(): number;
    isClosed(): boolean;
    getConnection(): Connection;
    cancel(): void;
    setEscapeProcessing(arg0: boolean): void;
    getLargeUpdateCount(): number;
    isCloseOnCompletion(): boolean;
    enquoteNCharLiteral(val: string): string;
    getResultSetHoldability(): number;
    getQueryTimeout(): number;
    setCursorName(arg0: string): void;
    getUpdateCount(): number;
    getResultSet(): ResultSet;
    getMoreResults(arg0: number): boolean;
    getMoreResults(): boolean;
    executeQuery(arg0: string): ResultSet;
    executeUpdate(arg0: string, arg1: Array<string>): number;
    executeUpdate(arg0: string, arg1: Array<number>): number;
    executeUpdate(arg0: string): number;
    executeUpdate(arg0: string, arg1: number): number;
    setMaxFieldSize(arg0: number): void;
    getMaxFieldSize(): number;
    getMaxRows(): number;
    setQueryTimeout(arg0: number): void;
    setMaxRows(arg0: number): void;
    getWarnings(): SQLWarning;
    clearWarnings(): void;
    executeLargeBatch(): Array<number>;
    getLargeMaxRows(): number;
    setFetchSize(arg0: number): void;
    executeLargeUpdate(sql: string, columnNames: Array<string>): number;
    executeLargeUpdate(sql: string, columnIndexes: Array<number>): number;
    executeLargeUpdate(sql: string, autoGeneratedKeys: number): number;
    executeLargeUpdate(sql: string): number;
    getFetchSize(): number;
    isSimpleIdentifier(identifier: string): boolean;
    isPoolable(): boolean;
    clearBatch(): void;
    addBatch(arg0: string): void;
    enquoteIdentifier(identifier: string, alwaysQuote: boolean): string;
    enquoteLiteral(val: string): string;
    setLargeMaxRows(max: number): void;
    closeOnCompletion(): void;
    getGeneratedKeys(): ResultSet;
    setPoolable(arg0: boolean): void;
    executeBatch(): Array<number>;
    getFetchDirection(): number;
    getResultSetType(): number;
    setFetchDirection(arg0: number): void;
    unwrap(arg0: any): any;
    isWrapperFor(arg0: any): boolean;
}
export declare class CallableStatement {
    static get $javaClass(): any;
    static get CLOSE_CURRENT_RESULT(): number;
    static get KEEP_CURRENT_RESULT(): number;
    static get CLOSE_ALL_RESULTS(): number;
    static get SUCCESS_NO_INFO(): number;
    static get EXECUTE_FAILED(): number;
    static get RETURN_GENERATED_KEYS(): number;
    static get NO_GENERATED_KEYS(): number;
}
