import Blob from '../../java/sql/Blob.js';
import CallableStatement from '../../java/sql/CallableStatement.js';
import Clob from '../../java/sql/Clob.js';
import DatabaseMetaData from '../../java/sql/DatabaseMetaData.js';
import NClob from '../../java/sql/NClob.js';
import PreparedStatement from '../../java/sql/PreparedStatement.js';
import SQLWarning from '../../java/sql/SQLWarning.js';
import SQLXML from '../../java/sql/SQLXML.js';
import Savepoint from '../../java/sql/Savepoint.js';
import ShardingKey from '../../java/sql/ShardingKey.js';
import Statement from '../../java/sql/Statement.js';
import Struct from '../../java/sql/Struct.js';
import _Array from '../../java/sql/Array.js';
export default interface Connection {
    setReadOnly(arg0: boolean): void;
    close(): void;
    isReadOnly(): boolean;
    abort(arg0: any): void;
    isValid(arg0: number): boolean;
    createStatement(arg0: number, arg1: number): Statement;
    createStatement(): Statement;
    createStatement(arg0: number, arg1: number, arg2: number): Statement;
    prepareStatement(arg0: string, arg1: number): PreparedStatement;
    prepareStatement(arg0: string): PreparedStatement;
    prepareStatement(arg0: string, arg1: number, arg2: number): PreparedStatement;
    prepareStatement(arg0: string, arg1: Array<string>): PreparedStatement;
    prepareStatement(arg0: string, arg1: number, arg2: number, arg3: number): PreparedStatement;
    prepareStatement(arg0: string, arg1: Array<number>): PreparedStatement;
    isClosed(): boolean;
    getMetaData(): DatabaseMetaData;
    getAutoCommit(): boolean;
    rollback(): void;
    rollback(arg0: Savepoint): void;
    createStruct(arg0: string, arg1: Array<any>): Struct;
    getTypeMap(): any;
    createArrayOf(arg0: string, arg1: Array<any>): _Array;
    getHoldability(): number;
    setClientInfo(arg0: string, arg1: string): void;
    setClientInfo(arg0: any): void;
    setCatalog(arg0: string): void;
    setSchema(arg0: string): void;
    setShardingKey(shardingKey: ShardingKey): void;
    setShardingKey(shardingKey: ShardingKey, superShardingKey: ShardingKey): void;
    setSavepoint(arg0: string): Savepoint;
    setSavepoint(): Savepoint;
    prepareCall(arg0: string, arg1: number, arg2: number): CallableStatement;
    prepareCall(arg0: string): CallableStatement;
    prepareCall(arg0: string, arg1: number, arg2: number, arg3: number): CallableStatement;
    setTypeMap(arg0: any): void;
    createBlob(): Blob;
    getNetworkTimeout(): number;
    createClob(): Clob;
    nativeSQL(arg0: string): string;
    setAutoCommit(arg0: boolean): void;
    setHoldability(arg0: number): void;
    getCatalog(): string;
    beginRequest(): void;
    commit(): void;
    createNClob(): NClob;
    getSchema(): string;
    releaseSavepoint(arg0: Savepoint): void;
    createSQLXML(): SQLXML;
    getClientInfo(): any;
    getClientInfo(arg0: string): string;
    endRequest(): void;
    setNetworkTimeout(arg0: any, arg1: number): void;
    setTransactionIsolation(arg0: number): void;
    getTransactionIsolation(): number;
    setShardingKeyIfValid(shardingKey: ShardingKey, superShardingKey: ShardingKey, timeout: number): boolean;
    setShardingKeyIfValid(shardingKey: ShardingKey, timeout: number): boolean;
    getWarnings(): SQLWarning;
    clearWarnings(): void;
    unwrap(arg0: any): any;
    isWrapperFor(arg0: any): boolean;
}
export default class Connection {
    static get $javaClass(): any;
    static get TRANSACTION_NONE(): number;
    static get TRANSACTION_READ_UNCOMMITTED(): number;
    static get TRANSACTION_READ_COMMITTED(): number;
    static get TRANSACTION_REPEATABLE_READ(): number;
    static get TRANSACTION_SERIALIZABLE(): number;
}
