import Keyed from '../../../org/bukkit/Keyed.js';
import NamespacedKey from '../../../org/bukkit/NamespacedKey.js';
export default interface Biome extends Keyed {
    getKey(): NamespacedKey;
    name(): string;
    compareTo(arg0: any): number;
    compareTo(o: any): number;
    getDeclaringClass(): any;
    ordinal(): number;
}
export default class Biome {
    static get $javaClass(): any;
    static get OCEAN(): Biome;
    static get PLAINS(): Biome;
    static get DESERT(): Biome;
    static get MOUNTAINS(): Biome;
    static get FOREST(): Biome;
    static get TAIGA(): Biome;
    static get SWAMP(): Biome;
    static get RIVER(): Biome;
    static get NETHER(): Biome;
    static get THE_END(): Biome;
    static get FROZEN_OCEAN(): Biome;
    static get FROZEN_RIVER(): Biome;
    static get SNOWY_TUNDRA(): Biome;
    static get SNOWY_MOUNTAINS(): Biome;
    static get MUSHROOM_FIELDS(): Biome;
    static get MUSHROOM_FIELD_SHORE(): Biome;
    static get BEACH(): Biome;
    static get DESERT_HILLS(): Biome;
    static get WOODED_HILLS(): Biome;
    static get TAIGA_HILLS(): Biome;
    static get MOUNTAIN_EDGE(): Biome;
    static get JUNGLE(): Biome;
    static get JUNGLE_HILLS(): Biome;
    static get JUNGLE_EDGE(): Biome;
    static get DEEP_OCEAN(): Biome;
    static get STONE_SHORE(): Biome;
    static get SNOWY_BEACH(): Biome;
    static get BIRCH_FOREST(): Biome;
    static get BIRCH_FOREST_HILLS(): Biome;
    static get DARK_FOREST(): Biome;
    static get SNOWY_TAIGA(): Biome;
    static get SNOWY_TAIGA_HILLS(): Biome;
    static get GIANT_TREE_TAIGA(): Biome;
    static get GIANT_TREE_TAIGA_HILLS(): Biome;
    static get WOODED_MOUNTAINS(): Biome;
    static get SAVANNA(): Biome;
    static get SAVANNA_PLATEAU(): Biome;
    static get BADLANDS(): Biome;
    static get WOODED_BADLANDS_PLATEAU(): Biome;
    static get BADLANDS_PLATEAU(): Biome;
    static get SMALL_END_ISLANDS(): Biome;
    static get END_MIDLANDS(): Biome;
    static get END_HIGHLANDS(): Biome;
    static get END_BARRENS(): Biome;
    static get WARM_OCEAN(): Biome;
    static get LUKEWARM_OCEAN(): Biome;
    static get COLD_OCEAN(): Biome;
    static get DEEP_WARM_OCEAN(): Biome;
    static get DEEP_LUKEWARM_OCEAN(): Biome;
    static get DEEP_COLD_OCEAN(): Biome;
    static get DEEP_FROZEN_OCEAN(): Biome;
    static get THE_VOID(): Biome;
    static get SUNFLOWER_PLAINS(): Biome;
    static get DESERT_LAKES(): Biome;
    static get GRAVELLY_MOUNTAINS(): Biome;
    static get FLOWER_FOREST(): Biome;
    static get TAIGA_MOUNTAINS(): Biome;
    static get SWAMP_HILLS(): Biome;
    static get ICE_SPIKES(): Biome;
    static get MODIFIED_JUNGLE(): Biome;
    static get MODIFIED_JUNGLE_EDGE(): Biome;
    static get TALL_BIRCH_FOREST(): Biome;
    static get TALL_BIRCH_HILLS(): Biome;
    static get DARK_FOREST_HILLS(): Biome;
    static get SNOWY_TAIGA_MOUNTAINS(): Biome;
    static get GIANT_SPRUCE_TAIGA(): Biome;
    static get GIANT_SPRUCE_TAIGA_HILLS(): Biome;
    static get MODIFIED_GRAVELLY_MOUNTAINS(): Biome;
    static get SHATTERED_SAVANNA(): Biome;
    static get SHATTERED_SAVANNA_PLATEAU(): Biome;
    static get ERODED_BADLANDS(): Biome;
    static get MODIFIED_WOODED_BADLANDS_PLATEAU(): Biome;
    static get MODIFIED_BADLANDS_PLATEAU(): Biome;
    static get BAMBOO_JUNGLE(): Biome;
    static get BAMBOO_JUNGLE_HILLS(): Biome;
}
