import { Location } from '../../../org/bukkit/Location.js';
import { BlockState } from '../../../org/bukkit/block/BlockState.js';
import { Material } from '../../../org/bukkit/Material.js';
import { World } from '../../../org/bukkit/World.js';
import { BoundingBox } from '../../../org/bukkit/util/BoundingBox.js';
import { PistonMoveReaction } from '../../../org/bukkit/block/PistonMoveReaction.js';
import { RayTraceResult } from '../../../org/bukkit/util/RayTraceResult.js';
import { Vector } from '../../../org/bukkit/util/Vector.js';
import { FluidCollisionMode } from '../../../org/bukkit/FluidCollisionMode.js';
import { Biome } from '../../../org/bukkit/block/Biome.js';
import { Chunk } from '../../../org/bukkit/Chunk.js';
import { BlockData } from '../../../org/bukkit/block/data/BlockData.js';
import { BlockFace } from '../../../org/bukkit/block/BlockFace.js';
import { ItemStack } from '../../../org/bukkit/inventory/ItemStack.js';
import { MetadataValue } from '../../../org/bukkit/metadata/MetadataValue.js';
import { Plugin } from '../../../org/bukkit/plugin/Plugin.js';
import { Metadatable } from '../../../org/bukkit/metadata/Metadatable.js';
export interface Block extends Metadatable {
    isEmpty(): boolean;
    getLocation(): Location;
    getLocation(arg0: Location): Location;
    getState(): BlockState;
    getType(): Material;
    getWorld(): World;
    getBoundingBox(): BoundingBox;
    getPistonMoveReaction(): PistonMoveReaction;
    getData(): number;
    setType(arg0: Material, arg1: boolean): void;
    setType(arg0: Material): void;
    rayTrace(arg0: Location, arg1: Vector, arg2: number, arg3: FluidCollisionMode): RayTraceResult;
    getBiome(): Biome;
    getHumidity(): number;
    setBiome(arg0: Biome): void;
    getTemperature(): number;
    getX(): number;
    getY(): number;
    getZ(): number;
    getChunk(): Chunk;
    getBlockData(): BlockData;
    isBlockIndirectlyPowered(): boolean;
    isBlockFaceIndirectlyPowered(arg0: BlockFace): boolean;
    getRelative(arg0: BlockFace, arg1: number): Block;
    getRelative(arg0: BlockFace): Block;
    getRelative(arg0: number, arg1: number, arg2: number): Block;
    getLightLevel(): number;
    getLightFromSky(): number;
    getLightFromBlocks(): number;
    setBlockData(arg0: BlockData, arg1: boolean): void;
    setBlockData(arg0: BlockData): void;
    getFace(arg0: Block): BlockFace;
    getBlockPower(arg0: BlockFace): number;
    getBlockPower(): number;
    isBlockPowered(): boolean;
    breakNaturally(): boolean;
    breakNaturally(arg0: ItemStack): boolean;
    isBlockFacePowered(arg0: BlockFace): boolean;
    isLiquid(): boolean;
    getDrops(arg0: ItemStack): any;
    getDrops(): any;
    isPassable(): boolean;
    hasMetadata(arg0: string): boolean;
    getMetadata(arg0: string): any;
    setMetadata(arg0: string, arg1: MetadataValue): void;
    removeMetadata(arg0: string, arg1: Plugin): void;
}
export declare class Block {
    static get $javaClass(): any;
}
