import Biome from '../../../org/bukkit/block/Biome.js';
import BlockData from '../../../org/bukkit/block/data/BlockData.js';
import BlockFace from '../../../org/bukkit/block/BlockFace.js';
import BlockState from '../../../org/bukkit/block/BlockState.js';
import BoundingBox from '../../../org/bukkit/util/BoundingBox.js';
import Chunk from '../../../org/bukkit/Chunk.js';
import FluidCollisionMode from '../../../org/bukkit/FluidCollisionMode.js';
import ItemStack from '../../../org/bukkit/inventory/ItemStack.js';
import Location from '../../../org/bukkit/Location.js';
import Material from '../../../org/bukkit/Material.js';
import MetadataValue from '../../../org/bukkit/metadata/MetadataValue.js';
import Metadatable from '../../../org/bukkit/metadata/Metadatable.js';
import PistonMoveReaction from '../../../org/bukkit/block/PistonMoveReaction.js';
import Plugin from '../../../org/bukkit/plugin/Plugin.js';
import RayTraceResult from '../../../org/bukkit/util/RayTraceResult.js';
import Vector from '../../../org/bukkit/util/Vector.js';
import World from '../../../org/bukkit/World.js';
export default interface Block extends Metadatable {
    isEmpty(): boolean;
    getLocation(arg0: Location): Location;
    getLocation(): Location;
    getState(): BlockState;
    getType(): Material;
    setType(arg0: Material): void;
    setType(arg0: Material, arg1: boolean): void;
    getData(): number;
    getBoundingBox(): BoundingBox;
    getWorld(): World;
    getPistonMoveReaction(): PistonMoveReaction;
    getDrops(arg0: ItemStack): any;
    getDrops(): any;
    getRelative(arg0: number, arg1: number, arg2: number): Block;
    getRelative(arg0: BlockFace, arg1: number): Block;
    getRelative(arg0: BlockFace): Block;
    isBlockFacePowered(arg0: BlockFace): boolean;
    breakNaturally(arg0: ItemStack): boolean;
    breakNaturally(): boolean;
    getLightLevel(): number;
    getLightFromSky(): number;
    getBlockPower(arg0: BlockFace): number;
    getBlockPower(): number;
    getLightFromBlocks(): number;
    getFace(arg0: Block): BlockFace;
    isBlockPowered(): boolean;
    isLiquid(): boolean;
    isPassable(): boolean;
    setBlockData(arg0: BlockData, arg1: boolean): void;
    setBlockData(arg0: BlockData): void;
    isBlockIndirectlyPowered(): boolean;
    isBlockFaceIndirectlyPowered(arg0: BlockFace): boolean;
    getBiome(): Biome;
    rayTrace(arg0: Location, arg1: Vector, arg2: number, arg3: FluidCollisionMode): RayTraceResult;
    setBiome(arg0: Biome): void;
    getTemperature(): number;
    getHumidity(): number;
    getBlockData(): BlockData;
    getZ(): number;
    getChunk(): Chunk;
    getY(): number;
    getX(): number;
    setMetadata(arg0: string, arg1: MetadataValue): void;
    removeMetadata(arg0: string, arg1: Plugin): void;
    getMetadata(arg0: string): Array<MetadataValue>;
    hasMetadata(arg0: string): boolean;
}
export default class Block {
    static get $javaClass(): any;
}
